AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for pdf2image

#
# Input Parameters
#
Parameters:
  Client:
    Description: Client Name
    Type: String
    Default: ""

Globals:
  Function:
    Timeout: 600
    MemorySize: 1024
    Environment:
      Variables:
#
# Resources
#
Resources:
  Image2PdfFunc:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      DockerTag: python3.9
      DockerContext: ./src/pdf2image_with_lambda
      Dockerfile: Dockerfile
